//CONSTANTS
export const DATABASE_TECHNOLOGY = 'sqlite'
export const DATABASE_NAME = 'OBSTACLE_HIRING.db'
export const DEFAULT_ACTION_LISTENER = 'SUCCEED'
export const WAIT_INTERVAL = 0
export const OBSTACLE_HIRING_TABLE = 'ObstacleHiring'
//ACTIONS
export const NAVIGATION_RESET = 'Navigation/RESET'
export const DEFAULT_STATE_SET = 'DEFAULT_STATE_SET'
export const OBSTACLE_HIRING_RETRIEVE = 'OBSTACLE_HIRING_RETRIEVE'
export const OBSTACLE_HIRE_ITEM_SELECTED = 'OBSTACLE_HIRE_ITEM_SELECTED'
export const SEARCHBAR_CHANGE = 'SEARCHBAR_CHANGE'
export const OBSTACLE_HIRING_TABLE_CREATE = 'OBSTACLE_HIRING_TABLE_CREATE'
export const OBSTACLE_HIRING_TABLE_DROP = 'OBSTACLE_HIRING_TABLE_DROP'
export const SEARCHBAR_TYPING = 'SEARCHBAR_TYPING'
export const OBSTACLE_HIRING_INITIALIZE = 'OBSTACLE_HIRING_INITIALIZE'
export const SEARCHBAR_FOCUSED = 'SEARCHBAR_FOCUSED'
//COLORS
export const TRANSPARENT = 'transparent'
export const GRAY_LOW_OPACITY = 'rgba(52,52,52,0.5)'
export const WHITE = 'white'
export const BLACK = 'black'